### ISSUE TITLE
OAPackage odd things when runsize is > 500

### ISSUE THREAD

**Issue by GeoMattB** [sebhaan/DoEgen#10]
Hi Seb,
this might be a feature of oapackage, or one of those "just me" problems. It's showing up in my multiproc results. I've posted a question to oapackage github about it.
I get a significant difference in the results when runsize is > 500. This looks like a limitation (feature) in oapackage. Arrays over 500 in size don't have efficiencies calculated, just a randomly generated design is returned.
It doesn't affect any work I'm doing at the moment as my runsizes are all below that. 

Example of the code where this is occurring.

```
import oapackage

runsize=600  ## change this to anything 500 and below for example of what I mean.
runtime=1000  
factor_levels=[6, 5, 4, 3]
number_of_factors=4
alpha = [5, 5, 15] # optimisation function
nrestarts=10
niter=10000
arrayclass = oapackage.arraydata_t(factor_levels, runsize, 0, number_of_factors)
    
scores, design_efficiencies, designs, ngenerated = oapackage.Doptim.Doptimize(
            arrayclass,
            nrestarts=nrestarts,
            niter=niter,
            optimfunc=alpha,
            nabort=3000,
            maxtime=runtime)
```

**Comment by GeoMattB** [comment]
I dug a little deeper into things and it looks a feature of oapackage.
![Screenshot 2023-05-13 155754](https://github.com/sebhaan/DoEgen/assets/29564171/91aaa2bf-e1d7-4604-b3d6-01c892cab7f4)

**Comment by GeoMattB** [comment]
The OApackage dev has increased the limit in the next version from 500 to 50000.
https://github.com/eendebakpt/oapackage/pull/232

**Comment by sebhaan** [comment]
Thanks for testing. Yes, that was a limitation of the oapackage. Great find of the next version update! I hope the next oapackage version will also work on Apple silicon, currently running in some problems with c compilers on Mac M1.

**Comment by GeoMattB** [comment]
The OApackge developer was pretty responsive when I flagged it, he didn't think it would be used on such large runsizes.

**Comment by sebhaan** [comment]
I can understand why larger sample sizes might not be the typical use case given that the aim for design arrays is primarily to provide an efficient test of some initial parameter/experiment space, which can then be evaluated and followed up with iterative optimisation schemes such as Bayesian optimisation.
