### ISSUE TITLE
efficiency print outputs clobber each other with multiprocessing

### ISSUE THREAD

**Issue by GeoMattB** [sebhaan/DoEgen#11]
The results that get printed to the screen during are out of order and don't make sense.
Mainly because the print statements us "," to string together outputs. 
If we just make them a string using + and some spaces then they print together and can be evaluated "on the fly" if needed.
Aslo, I think it would be useful to simplify the outputs a little and include in the output the number of arrays Doptimize produces so we can determine whats happening with the interaction between runsize and max-runtime.

**Comment by sebhaan** [comment]
not sure which exact print statements you are referring to, but it might make sense to suppress all while multiprocessing and to replace with progress bar (e.g. tqdm) or spinner function. Designs and efficiencies are saved for each runsize anyway, so one could add the output number of arrays to these files as well.

**Comment by GeoMattB** [comment]
I like this as a simple output, the shorter runsizes finish faster so those results get returned first, if it was all completing in the same time they'd get returned randomly. I like how the this gives an idea of where the results are heading.

![image](https://github.com/sebhaan/DoEgen/assets/29564171/264481f0-2561-4869-a739-58e6c2db1027)

**Comment by GeoMattB** [comment]
Closing this as I've created PR #12 to address this.
