### ISSUE TITLE
add current github version to pip

### ISSUE THREAD

**Issue by GeoMattB** [sebhaan/DoEgen#14]
Hi Seb,
is it possible to push the github version of DoEgen to pip?

Thanks
Matt

**Comment by sebhaan** [comment]
Hi,
thanks for the latest pull request.  Will look into that, however currently OApackage can't be installed on mac arm M1/M2, which is a major dependency for DoEgen. OApackage fails to compile (related to this [issue](https://github.com/eendebakpt/oapackage/issues/224)) after multiple trials (swig and numpy installed).

**Comment by sebhaan** [comment]
New pip install available for DoEgen [0.5.0](https://pypi.org/project/DoEgen/0.5.0/)! This now also supports Apple M1/M2 given the latest OApackage release (2.7.11).

**Comment by GeoMattB** [comment]
This sparks joy. Thanks Seb, I appreciate the work you've put into this.
