### ISSUE TITLE
identify variables in output csv files

### ISSUE THREAD

**Issue by hlydecker** [sebhaan/DoEgen#3]
Currently the output .csv files do not specify what each column actually represents. 

There should be some sort of representation of what each of these columns represents. 

If we want this to be a general purpose tool, we might need a key/dictionary file with the identity of each column.

Or we could just include the actual variable names as column headers.

**Comment by sebhaan** [comment]
Variable names are included in  output csv files. The default variable test was named Factor 1,2,3.... that's why it may have looked like without names.
