### ISSUE TITLE
openpyxl requirement

### ISSUE THREAD

**Issue by GeoMattB** [sebhaan/DoEgen#4]
I'm getting this error but both of these are installed, there's a missing comma after the openpyxl requirement in setup.py

ERROR: Could not find a version that satisfies the requirement openpyxl>=3.0.7seaborn>=0.11.1 (from DoEgen) <...... list of versions available>.

I'm using WSL on windows 10, ubuntu 20.04. I successfully installed DoEgen on another PC prior to this change.

**Comment by sebhaan** [comment]
thanks for pointing out the missing comma. This has been fixed now in setup.py.
