### ISSUE TITLE
doeval factor importance

### ISSUE THREAD

**Issue by GeoMattB** [sebhaan/DoEgen#6]
Hi Seb,
I had another dig in to doeval and it looks like it only uses the top 10 results to calculate the factor importance. I may be missing something though. Is it possible to have this for the top 10 and all experiments?

**Comment by sebhaan** [comment]
Hi, can you provide some more details? Assuming you mean the parameter importance calculated in doeval.calc_expresults_stats()? This is calculated before the top 10 results are selected at the end of the function, so on all data in the inout dataframe dfres. If you like to calculate the importance only for the top 10 then you could call doeval.calc_expresults_stats(ylabels, dfdes, dfres, outpath) with the input dataframes dfdes and dfres containing only the top 10.

**Comment by GeoMattB** [comment]
Thanks,
Okay, that should help, obbviously something I've missed but it might be a while before I get back into this. I'll close the issue. Thanks again.
Matt
